// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 

    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even valued terms.

#include <iostream>

int even_fib_sum(int limit);

int main()
{
    std::cout << even_fib_sum(4000000) << std::endl;
    return 0;
}

int even_fib_sum(int limit)
{
    int a = 1;
    int b = 2;
    int temp = 0;

    int sum = 0;

    while (b <= limit)
    {
        if (b % 2 == 0) { sum += b; }
        // a, b = b, a + b;
        temp = a + b;
        a = b;
        b = temp;
    }

    return sum;
}
