/*
    Each new term in the Fibonacci Sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...

    By considering the terms in the Fibonacci Sequence whose values do not exceed four million, find the sum of the even valued terms.
*/

public class ProblemTwo 
{
    
    // Solver method
    public static void evenFibonacciNumbers()
    {
        int init = 0;
        int fib = 1;
        int nxt = fib;
        int sum = 0;

        while(nxt < 4000000)
        {
            init = fib;
            fib = nxt;
            nxt = init + fib;

            if(fib % 2 == 0)
            {
                sum = sum + fib;
            }
        }

        System.out.println(sum);
    }
    
    // Main method
    public static void main(String[] args) 
    {
       evenFibonacciNumbers(); 
    }
}
