# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 

    # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even valued terms.



##############################
### EVEN FIBONACCI NUMBERS ###
##############################



import math

num1 = 0
num2 = 1
nextNum = num2
max = 0
sum = 0

while max <= 4000000:
    num1, num2 = num2, nextNum
    nextNum = num1 + num2
    max = 0 + nextNum
    if nextNum % 2 == 0:
        sum = sum + nextNum

print(sum)

# def evenFibSum(limit):
#     a, b = 1, 2
#     total = 0
#     while b <= limit:
#         if b % 2 == 0:
#             total += b
#         a, b = b, a + b
#     return total

# print(evenFibSum(int(input("Limit? : "))))