# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be:

    # 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28

# Let us list the factors of the first sevent triangle numbers:

    # 1 : 1
    # 3 : 1, 3
    # 6 : 1, 2, 3, 6
    # 10 : 1, 2, 5, 10
    # 15 : 1, 3, 5, 15
    # 21 : 1, 3, 7, 21
    # 28 : 1, 2, 4, 7, 14, 28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?



########################################
### HIGHLY DIVISIBLE TRIANGLE NUMBER ###
########################################


def calculate_triangle_number(n):
    total = 1
    for i in range(n, 1, -1):
        total += i
    return total

def number_of_divisors(n):
    divisors = set()
    
    for i in range(1, n + 1):
        if n % i == 0:
            divisors.add(i)

    return len(divisors)







        

